http:
  host: localhost
  port: 8080
redis:
  host: localhost
  port: 6379
  db: 0
  password:
mysql:
  host: localhost
  port: 3306
  user: tiktok
  password: tiktok
  database: tiktok
s3:
  accesskey:
  secretkey:
  bucket:
  region:
kafka:
  brokers:
    - localhost:9092
