debug: true
http:
  host: 0.0.0.0
  port: 8080
redis:
  vaild: true
  host: redis
  port: 6379
  db: 0
  password:
mysql:
  host: mariadb
  port: 3306
  user: tiktok
  password: tiktok
  database: tiktok
s3:
  vaild: false
  endpoint: 
  accesskey: 
  secretkey: 
  bucket: 
  region: 
kafka:
  vaild: false
  brokers:
    - localhost:9092
